.PHONY: infra-up infra-health infra-down test lint run

infra-up:
	./scripts/manage.sh infra-up

infra-health:
	@./scripts/manage.sh infra-health

infra-down:
	./scripts/manage.sh infra-down

test:
	./scripts/manage.sh test

lint:
	./scripts/manage.sh lint

run:
	./scripts/manage.sh run
