/**
 * Chinese Kinship Term Calculator Engine
 *
 * Comprehensive kinship term database built from the mumuy/relationship
 * dataset (MIT license, github.com/mumuy/relationship). Contains 550+
 * relationship chain mappings covering direct family, extended paternal
 * and maternal lines, in-laws, spouse's family, and remote ancestors.
 *
 * Uses a chain-based approach: each button click appends a relationship
 * code to the chain. The engine applies normalization rules iteratively
 * to reduce the chain, then looks up the result in a comprehensive map.
 *
 * Codes: f=father, m=mother, ob=older_brother, lb=younger_brother,
 *        os=older_sister, ls=younger_sister, s=son, d=daughter,
 *        h=husband, w=wife
 */
const KinshipEngine = (() => {

  const RELATIONS = [
    { id: 'f',  label: '爸爸' },
    { id: 'm',  label: '妈妈' },
    { id: 'ob', label: '哥哥' },
    { id: 'lb', label: '弟弟' },
    { id: 'os', label: '姐姐' },
    { id: 'ls', label: '妹妹' },
    { id: 's',  label: '儿子' },
    { id: 'd',  label: '女儿' },
    { id: 'h',  label: '老公' },
    { id: 'w',  label: '老婆' },
  ];

  // ── Normalization rules ──────────────────────────────────────
  // Applied iteratively on the dot-joined chain until stable.
  // Order matters: more specific patterns first.
  const RULES = [
    // Spouse of spouse = self (cancel out)
    ['h.w', ''],
    ['w.h', ''],

    // Sibling's parent = my parent
    ['ob.f', 'f'], ['ob.m', 'm'],
    ['lb.f', 'f'], ['lb.m', 'm'],
    ['os.f', 'f'], ['os.m', 'm'],
    ['ls.f', 'f'], ['ls.m', 'm'],

    // Child's same-gender parent = self
    // (your son's father = you, your daughter's father = you)
    ['s.f', ''], ['d.f', ''],
    // Child's other parent = spouse
    ['s.m', 'w'], ['d.m', 'w'],

    // Parent's child → sibling
    // We default to ob/os since the parent being older implies context.
    ['f.s', 'ob'], ['f.d', 'os'],
    ['m.s', 'ob'], ['m.d', 'os'],
  ];

  // ── Comprehensive kinship term map ───────────────────────────
  // Key = dot-joined code chain, Value = { term, explanation }
  // Data sourced from mumuy/relationship (MIT) + supplemental entries
  const MAP = {
    'd': { term: '女儿', explanation: '你的女儿' },
    'f': { term: '爸爸', explanation: '你的父亲' },
    'h': { term: '老公', explanation: '你的丈夫' },
    'lb': { term: '弟弟', explanation: '你的弟弟' },
    'ls': { term: '妹妹', explanation: '你的妹妹' },
    'm': { term: '妈妈', explanation: '你的母亲' },
    'ob': { term: '哥哥', explanation: '你的哥哥' },
    'os': { term: '姐姐', explanation: '你的姐姐' },
    's': { term: '儿子', explanation: '你的儿子' },
    'w': { term: '老婆', explanation: '你的妻子' },
    'd.d': { term: '外孙女', explanation: '女儿的女儿' },
    'd.h': { term: '女婿', explanation: '女儿的丈夫' },
    'd.s': { term: '外孙', explanation: '女儿的儿子' },
    'f.f': { term: '爷爷', explanation: '爸爸的爸爸' },
    'f.lb': { term: '叔叔', explanation: '爸爸的弟弟' },
    'f.ls': { term: '小姑', explanation: '爸爸的妹妹' },
    'f.m': { term: '奶奶', explanation: '爸爸的妈妈' },
    'f.ob': { term: '伯父', explanation: '爸爸的哥哥' },
    'f.os': { term: '大姑', explanation: '爸爸的姐姐' },
    'h.f': { term: '公公', explanation: '丈夫的爸爸' },
    'h.lb': { term: '小叔子', explanation: '丈夫的弟弟' },
    'h.ls': { term: '小姑子', explanation: '丈夫的妹妹' },
    'h.m': { term: '婆婆', explanation: '丈夫的妈妈' },
    'h.ob': { term: '大伯子', explanation: '丈夫的哥哥' },
    'h.os': { term: '大姑子', explanation: '丈夫的姐姐' },
    'lb.d': { term: '侄女', explanation: '弟弟的女儿' },
    'lb.s': { term: '侄子', explanation: '弟弟的儿子' },
    'lb.w': { term: '弟妹', explanation: '弟弟的妻子' },
    'ls.d': { term: '外甥女', explanation: '妹妹的女儿' },
    'ls.h': { term: '妹夫', explanation: '妹妹的丈夫' },
    'ls.s': { term: '外甥', explanation: '妹妹的儿子' },
    'm.f': { term: '外公', explanation: '妈妈的爸爸' },
    'm.lb': { term: '小舅', explanation: '妈妈的弟弟' },
    'm.ls': { term: '小姨', explanation: '妈妈的妹妹' },
    'm.m': { term: '外婆', explanation: '妈妈的妈妈' },
    'm.ob': { term: '大舅', explanation: '妈妈的哥哥' },
    'm.os': { term: '大姨', explanation: '妈妈的姐姐' },
    'ob.d': { term: '侄女', explanation: '哥哥的女儿' },
    'ob.s': { term: '侄子', explanation: '哥哥的儿子' },
    'ob.w': { term: '嫂子', explanation: '哥哥的妻子' },
    'os.d': { term: '外甥女', explanation: '姐姐的女儿' },
    'os.h': { term: '姐夫', explanation: '姐姐的丈夫' },
    'os.s': { term: '外甥', explanation: '姐姐的儿子' },
    's.d': { term: '孙女', explanation: '儿子的女儿' },
    's.s': { term: '孙子', explanation: '儿子的儿子' },
    's.w': { term: '儿媳', explanation: '儿子的妻子' },
    'w.f': { term: '岳父', explanation: '妻子的爸爸' },
    'w.lb': { term: '小舅子', explanation: '妻子的弟弟' },
    'w.ls': { term: '小姨子', explanation: '妻子的妹妹' },
    'w.m': { term: '岳母', explanation: '妻子的妈妈' },
    'w.ob': { term: '大舅子', explanation: '妻子的哥哥' },
    'w.os': { term: '大姨子', explanation: '妻子的姐姐' },
    'd.d.d': { term: '外曾外孙女', explanation: '女儿的女儿的女儿' },
    'd.d.h': { term: '外孙女婿', explanation: '女儿的女儿的丈夫' },
    'd.d.s': { term: '外曾外孙', explanation: '女儿的女儿的儿子' },
    'd.h.f': { term: '亲家公', explanation: '女儿的丈夫的爸爸' },
    'd.h.lb': { term: '姻侄', explanation: '女儿的丈夫的弟弟' },
    'd.h.ls': { term: '姻侄女', explanation: '女儿的丈夫的妹妹' },
    'd.h.m': { term: '亲家母', explanation: '女儿的丈夫的妈妈' },
    'd.h.ob': { term: '姻侄', explanation: '女儿的丈夫的哥哥' },
    'd.h.os': { term: '姻侄女', explanation: '女儿的丈夫的姐姐' },
    'd.s.d': { term: '外曾孙女', explanation: '女儿的儿子的女儿' },
    'd.s.s': { term: '外曾孙', explanation: '女儿的儿子的儿子' },
    'd.s.w': { term: '外孙媳妇', explanation: '女儿的儿子的妻子' },
    'f.f.f': { term: '曾祖父', explanation: '爸爸的爸爸的爸爸' },
    'f.f.lb': { term: '叔公', explanation: '爸爸的爸爸的弟弟' },
    'f.f.ls': { term: '姑奶奶', explanation: '爸爸的爸爸的妹妹' },
    'f.f.m': { term: '曾祖母', explanation: '爸爸的爸爸的妈妈' },
    'f.f.ob': { term: '伯公', explanation: '爸爸的爸爸的哥哥' },
    'f.f.os': { term: '姑奶奶', explanation: '爸爸的爸爸的姐姐' },
    'f.lb.d': { term: '堂妹', explanation: '爸爸的弟弟的女儿' },
    'f.lb.s': { term: '堂弟', explanation: '爸爸的弟弟的儿子' },
    'f.lb.w': { term: '婶婶', explanation: '爸爸的弟弟的妻子' },
    'f.ls.d': { term: '表妹', explanation: '爸爸的妹妹的女儿' },
    'f.ls.h': { term: '小姑丈', explanation: '爸爸的妹妹的丈夫' },
    'f.ls.s': { term: '表弟', explanation: '爸爸的妹妹的儿子' },
    'f.m.f': { term: '曾外祖父', explanation: '爸爸的妈妈的爸爸' },
    'f.m.lb': { term: '小舅爷', explanation: '爸爸的妈妈的弟弟' },
    'f.m.ls': { term: '姨奶奶', explanation: '爸爸的妈妈的妹妹' },
    'f.m.m': { term: '曾外祖母', explanation: '爸爸的妈妈的妈妈' },
    'f.m.ob': { term: '大舅爷', explanation: '爸爸的妈妈的哥哥' },
    'f.m.os': { term: '姨奶奶', explanation: '爸爸的妈妈的姐姐' },
    'f.ob.d': { term: '堂姐', explanation: '爸爸的哥哥的女儿' },
    'f.ob.s': { term: '堂哥', explanation: '爸爸的哥哥的儿子' },
    'f.ob.w': { term: '伯母', explanation: '爸爸的哥哥的妻子' },
    'f.os.d': { term: '表姐', explanation: '爸爸的姐姐的女儿' },
    'f.os.h': { term: '大姑丈', explanation: '爸爸的姐姐的丈夫' },
    'f.os.s': { term: '表哥', explanation: '爸爸的姐姐的儿子' },
    'h.f.f': { term: '祖公父', explanation: '丈夫的爸爸的爸爸' },
    'h.f.lb': { term: '叔公父', explanation: '丈夫的爸爸的弟弟' },
    'h.f.ls': { term: '姑婆母', explanation: '丈夫的爸爸的妹妹' },
    'h.f.m': { term: '祖婆母', explanation: '丈夫的爸爸的妈妈' },
    'h.f.ob': { term: '伯公父', explanation: '丈夫的爸爸的哥哥' },
    'h.f.os': { term: '姑婆母', explanation: '丈夫的爸爸的姐姐' },
    'h.lb.d': { term: '叔侄女', explanation: '丈夫的弟弟的女儿' },
    'h.lb.s': { term: '叔侄', explanation: '丈夫的弟弟的儿子' },
    'h.lb.w': { term: '小婶子', explanation: '丈夫的弟弟的妻子' },
    'h.ls.d': { term: '姑甥女', explanation: '丈夫的妹妹的女儿' },
    'h.ls.h': { term: '小姑夫', explanation: '丈夫的妹妹的丈夫' },
    'h.ls.s': { term: '姑甥', explanation: '丈夫的妹妹的儿子' },
    'h.m.f': { term: '外祖公父', explanation: '丈夫的妈妈的爸爸' },
    'h.m.lb': { term: '舅公父', explanation: '丈夫的妈妈的弟弟' },
    'h.m.ls': { term: '姨婆母', explanation: '丈夫的妈妈的妹妹' },
    'h.m.m': { term: '外祖婆母', explanation: '丈夫的妈妈的妈妈' },
    'h.m.ob': { term: '舅公父', explanation: '丈夫的妈妈的哥哥' },
    'h.m.os': { term: '姨婆母', explanation: '丈夫的妈妈的姐姐' },
    'h.ob.d': { term: '叔侄女', explanation: '丈夫的哥哥的女儿' },
    'h.ob.s': { term: '叔侄', explanation: '丈夫的哥哥的儿子' },
    'h.ob.w': { term: '大婶子', explanation: '丈夫的哥哥的妻子' },
    'h.os.d': { term: '姑甥女', explanation: '丈夫的姐姐的女儿' },
    'h.os.h': { term: '大姑夫', explanation: '丈夫的姐姐的丈夫' },
    'h.os.s': { term: '姑甥', explanation: '丈夫的姐姐的儿子' },
    'lb.d.d': { term: '侄外孙女', explanation: '弟弟的女儿的女儿' },
    'lb.d.h': { term: '侄女婿', explanation: '弟弟的女儿的丈夫' },
    'lb.d.s': { term: '侄外孙', explanation: '弟弟的女儿的儿子' },
    'lb.s.d': { term: '侄孙女', explanation: '弟弟的儿子的女儿' },
    'lb.s.s': { term: '侄孙', explanation: '弟弟的儿子的儿子' },
    'lb.s.w': { term: '侄媳妇', explanation: '弟弟的儿子的妻子' },
    'ls.d.d': { term: '外甥外孙女', explanation: '妹妹的女儿的女儿' },
    'ls.d.h': { term: '甥女婿', explanation: '妹妹的女儿的丈夫' },
    'ls.d.s': { term: '外甥外孙', explanation: '妹妹的女儿的儿子' },
    'ls.s.d': { term: '甥孙女', explanation: '妹妹的儿子的女儿' },
    'ls.s.s': { term: '甥孙', explanation: '妹妹的儿子的儿子' },
    'ls.s.w': { term: '甥媳妇', explanation: '妹妹的儿子的妻子' },
    'm.f.f': { term: '外曾祖父', explanation: '妈妈的爸爸的爸爸' },
    'm.f.lb': { term: '叔外公', explanation: '妈妈的爸爸的弟弟' },
    'm.f.ls': { term: '姑外婆', explanation: '妈妈的爸爸的妹妹' },
    'm.f.m': { term: '外曾祖母', explanation: '妈妈的爸爸的妈妈' },
    'm.f.ob': { term: '伯外公', explanation: '妈妈的爸爸的哥哥' },
    'm.f.os': { term: '姑外婆', explanation: '妈妈的爸爸的姐姐' },
    'm.lb.d': { term: '表妹', explanation: '妈妈的弟弟的女儿' },
    'm.lb.s': { term: '表弟', explanation: '妈妈的弟弟的儿子' },
    'm.lb.w': { term: '小舅妈', explanation: '妈妈的弟弟的妻子' },
    'm.ls.d': { term: '表妹', explanation: '妈妈的妹妹的女儿' },
    'm.ls.h': { term: '小姨丈', explanation: '妈妈的妹妹的丈夫' },
    'm.ls.s': { term: '表弟', explanation: '妈妈的妹妹的儿子' },
    'm.m.f': { term: '外曾外祖父', explanation: '妈妈的妈妈的爸爸' },
    'm.m.lb': { term: '舅外公', explanation: '妈妈的妈妈的弟弟' },
    'm.m.ls': { term: '姨外婆', explanation: '妈妈的妈妈的妹妹' },
    'm.m.m': { term: '外曾外祖母', explanation: '妈妈的妈妈的妈妈' },
    'm.m.ob': { term: '舅外公', explanation: '妈妈的妈妈的哥哥' },
    'm.m.os': { term: '姨外婆', explanation: '妈妈的妈妈的姐姐' },
    'm.ob.d': { term: '表姐', explanation: '妈妈的哥哥的女儿' },
    'm.ob.s': { term: '表哥', explanation: '妈妈的哥哥的儿子' },
    'm.ob.w': { term: '大舅妈', explanation: '妈妈的哥哥的妻子' },
    'm.os.d': { term: '表姐', explanation: '妈妈的姐姐的女儿' },
    'm.os.h': { term: '大姨丈', explanation: '妈妈的姐姐的丈夫' },
    'm.os.s': { term: '表哥', explanation: '妈妈的姐姐的儿子' },
    'ob.d.d': { term: '侄外孙女', explanation: '哥哥的女儿的女儿' },
    'ob.d.h': { term: '侄女婿', explanation: '哥哥的女儿的丈夫' },
    'ob.d.s': { term: '侄外孙', explanation: '哥哥的女儿的儿子' },
    'ob.s.d': { term: '侄孙女', explanation: '哥哥的儿子的女儿' },
    'ob.s.s': { term: '侄孙', explanation: '哥哥的儿子的儿子' },
    'ob.s.w': { term: '侄媳妇', explanation: '哥哥的儿子的妻子' },
    'os.d.d': { term: '外甥外孙女', explanation: '姐姐的女儿的女儿' },
    'os.d.h': { term: '甥女婿', explanation: '姐姐的女儿的丈夫' },
    'os.d.s': { term: '外甥外孙', explanation: '姐姐的女儿的儿子' },
    'os.s.d': { term: '甥孙女', explanation: '姐姐的儿子的女儿' },
    'os.s.s': { term: '甥孙', explanation: '姐姐的儿子的儿子' },
    'os.s.w': { term: '甥媳妇', explanation: '姐姐的儿子的妻子' },
    's.d.d': { term: '曾外孙女', explanation: '儿子的女儿的女儿' },
    's.d.h': { term: '孙女婿', explanation: '儿子的女儿的丈夫' },
    's.d.s': { term: '曾外孙', explanation: '儿子的女儿的儿子' },
    's.s.d': { term: '曾孙女', explanation: '儿子的儿子的女儿' },
    's.s.s': { term: '曾孙', explanation: '儿子的儿子的儿子' },
    's.s.w': { term: '孙媳妇', explanation: '儿子的儿子的妻子' },
    's.w.f': { term: '亲家公', explanation: '儿子的妻子的爸爸' },
    's.w.lb': { term: '姻侄', explanation: '儿子的妻子的弟弟' },
    's.w.ls': { term: '姻侄女', explanation: '儿子的妻子的妹妹' },
    's.w.m': { term: '亲家母', explanation: '儿子的妻子的妈妈' },
    's.w.ob': { term: '姻侄', explanation: '儿子的妻子的哥哥' },
    's.w.os': { term: '姻侄女', explanation: '儿子的妻子的姐姐' },
    'w.f.f': { term: '祖岳父', explanation: '妻子的爸爸的爸爸' },
    'w.f.lb': { term: '叔岳父', explanation: '妻子的爸爸的弟弟' },
    'w.f.m': { term: '祖岳母', explanation: '妻子的爸爸的妈妈' },
    'w.f.ob': { term: '伯岳父', explanation: '妻子的爸爸的哥哥' },
    'w.lb.d': { term: '舅侄女', explanation: '妻子的弟弟的女儿' },
    'w.lb.s': { term: '舅侄', explanation: '妻子的弟弟的儿子' },
    'w.lb.w': { term: '小舅妇', explanation: '妻子的弟弟的妻子' },
    'w.ls.d': { term: '姨甥女', explanation: '妻子的妹妹的女儿' },
    'w.ls.h': { term: '小姨夫', explanation: '妻子的妹妹的丈夫' },
    'w.ls.s': { term: '姨甥', explanation: '妻子的妹妹的儿子' },
    'w.m.f': { term: '外祖岳父', explanation: '妻子的妈妈的爸爸' },
    'w.m.lb': { term: '舅岳父', explanation: '妻子的妈妈的弟弟' },
    'w.m.m': { term: '外祖岳母', explanation: '妻子的妈妈的妈妈' },
    'w.m.ob': { term: '舅岳父', explanation: '妻子的妈妈的哥哥' },
    'w.ob.d': { term: '舅侄女', explanation: '妻子的哥哥的女儿' },
    'w.ob.s': { term: '舅侄', explanation: '妻子的哥哥的儿子' },
    'w.ob.w': { term: '大舅妇', explanation: '妻子的哥哥的妻子' },
    'w.os.d': { term: '姨甥女', explanation: '妻子的姐姐的女儿' },
    'w.os.h': { term: '大姨夫', explanation: '妻子的姐姐的丈夫' },
    'w.os.s': { term: '姨甥', explanation: '妻子的姐姐的儿子' },
    'd.d.d.d': { term: '外曾外曾外孙女', explanation: '女儿的女儿的女儿的女儿' },
    'd.d.d.h': { term: '外曾外孙女婿', explanation: '女儿的女儿的女儿的丈夫' },
    'd.d.d.s': { term: '外曾外曾外孙', explanation: '女儿的女儿的女儿的儿子' },
    'd.d.s.d': { term: '外曾外曾孙女', explanation: '女儿的女儿的儿子的女儿' },
    'd.d.s.s': { term: '外曾外曾孙', explanation: '女儿的女儿的儿子的儿子' },
    'd.d.s.w': { term: '外曾外孙媳妇', explanation: '女儿的女儿的儿子的妻子' },
    'd.h.f.f': { term: '姻伯', explanation: '女儿的丈夫的爸爸的爸爸' },
    'd.h.lb.d': { term: '姻侄孙女', explanation: '女儿的丈夫的弟弟的女儿' },
    'd.h.lb.s': { term: '姻侄孙', explanation: '女儿的丈夫的弟弟的儿子' },
    'd.h.lb.w': { term: '姻侄媳', explanation: '女儿的丈夫的弟弟的妻子' },
    'd.h.ls.d': { term: '姻侄外孙女', explanation: '女儿的丈夫的妹妹的女儿' },
    'd.h.ls.h': { term: '姻侄婿', explanation: '女儿的丈夫的妹妹的丈夫' },
    'd.h.ls.s': { term: '姻侄外孙', explanation: '女儿的丈夫的妹妹的儿子' },
    'd.h.ob.d': { term: '姻侄孙女', explanation: '女儿的丈夫的哥哥的女儿' },
    'd.h.ob.s': { term: '姻侄孙', explanation: '女儿的丈夫的哥哥的儿子' },
    'd.h.ob.w': { term: '姻侄媳', explanation: '女儿的丈夫的哥哥的妻子' },
    'd.h.os.d': { term: '姻侄外孙女', explanation: '女儿的丈夫的姐姐的女儿' },
    'd.h.os.h': { term: '姻侄婿', explanation: '女儿的丈夫的姐姐的丈夫' },
    'd.h.os.s': { term: '姻侄外孙', explanation: '女儿的丈夫的姐姐的儿子' },
    'd.s.d.d': { term: '外玄外孙女', explanation: '女儿的儿子的女儿的女儿' },
    'd.s.d.h': { term: '外曾孙女婿', explanation: '女儿的儿子的女儿的丈夫' },
    'd.s.d.s': { term: '外玄外孙', explanation: '女儿的儿子的女儿的儿子' },
    'd.s.s.d': { term: '外玄孙女', explanation: '女儿的儿子的儿子的女儿' },
    'd.s.s.s': { term: '外玄孙', explanation: '女儿的儿子的儿子的儿子' },
    'd.s.s.w': { term: '外曾孙媳妇', explanation: '女儿的儿子的儿子的妻子' },
    'f.f.f.f': { term: '高祖父', explanation: '爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.lb': { term: '伯叔曾祖父', explanation: '爸爸的爸爸的爸爸的弟弟' },
    'f.f.f.m': { term: '高祖母', explanation: '爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.ob': { term: '伯叔曾祖父', explanation: '爸爸的爸爸的爸爸的哥哥' },
    'f.f.lb.d': { term: '堂姑', explanation: '爸爸的爸爸的弟弟的女儿' },
    'f.f.lb.s': { term: '堂叔', explanation: '爸爸的爸爸的弟弟的儿子' },
    'f.f.lb.w': { term: '叔婆', explanation: '爸爸的爸爸的弟弟的妻子' },
    'f.f.ls.h': { term: '姑爷爷', explanation: '爸爸的爸爸的妹妹的丈夫' },
    'f.f.m.f': { term: '高外祖父', explanation: '爸爸的爸爸的妈妈的爸爸' },
    'f.f.m.m': { term: '高外祖母', explanation: '爸爸的爸爸的妈妈的妈妈' },
    'f.f.ob.d': { term: '堂姑', explanation: '爸爸的爸爸的哥哥的女儿' },
    'f.f.ob.s': { term: '堂伯', explanation: '爸爸的爸爸的哥哥的儿子' },
    'f.f.ob.w': { term: '伯婆', explanation: '爸爸的爸爸的哥哥的妻子' },
    'f.f.os.h': { term: '姑爷爷', explanation: '爸爸的爸爸的姐姐的丈夫' },
    'f.lb.d.d': { term: '堂外甥女', explanation: '爸爸的弟弟的女儿的女儿' },
    'f.lb.d.h': { term: '堂妹夫', explanation: '爸爸的弟弟的女儿的丈夫' },
    'f.lb.d.s': { term: '堂外甥', explanation: '爸爸的弟弟的女儿的儿子' },
    'f.lb.s.d': { term: '堂侄女', explanation: '爸爸的弟弟的儿子的女儿' },
    'f.lb.s.s': { term: '堂侄', explanation: '爸爸的弟弟的儿子的儿子' },
    'f.lb.s.w': { term: '堂弟媳', explanation: '爸爸的弟弟的儿子的妻子' },
    'f.ls.d.d': { term: '表外甥女', explanation: '爸爸的妹妹的女儿的女儿' },
    'f.ls.d.h': { term: '表妹夫', explanation: '爸爸的妹妹的女儿的丈夫' },
    'f.ls.d.s': { term: '表外甥', explanation: '爸爸的妹妹的女儿的儿子' },
    'f.ls.s.d': { term: '表侄女', explanation: '爸爸的妹妹的儿子的女儿' },
    'f.ls.s.s': { term: '表侄', explanation: '爸爸的妹妹的儿子的儿子' },
    'f.ls.s.w': { term: '表弟妹', explanation: '爸爸的妹妹的儿子的妻子' },
    'f.m.f.f': { term: '曾外曾祖父', explanation: '爸爸的妈妈的爸爸的爸爸' },
    'f.m.f.m': { term: '曾外曾祖母', explanation: '爸爸的妈妈的爸爸的妈妈' },
    'f.m.lb.w': { term: '小舅婆', explanation: '爸爸的妈妈的弟弟的妻子' },
    'f.m.ls.h': { term: '姨爷爷', explanation: '爸爸的妈妈的妹妹的丈夫' },
    'f.m.m.f': { term: '曾外曾外祖父', explanation: '爸爸的妈妈的妈妈的爸爸' },
    'f.m.m.m': { term: '曾外曾外祖母', explanation: '爸爸的妈妈的妈妈的妈妈' },
    'f.m.ob.w': { term: '大舅婆', explanation: '爸爸的妈妈的哥哥的妻子' },
    'f.m.os.h': { term: '姨爷爷', explanation: '爸爸的妈妈的姐姐的丈夫' },
    'f.ob.d.d': { term: '堂外甥女', explanation: '爸爸的哥哥的女儿的女儿' },
    'f.ob.d.h': { term: '堂姐夫', explanation: '爸爸的哥哥的女儿的丈夫' },
    'f.ob.d.s': { term: '堂外甥', explanation: '爸爸的哥哥的女儿的儿子' },
    'f.ob.s.d': { term: '堂侄女', explanation: '爸爸的哥哥的儿子的女儿' },
    'f.ob.s.s': { term: '堂侄', explanation: '爸爸的哥哥的儿子的儿子' },
    'f.ob.s.w': { term: '堂嫂', explanation: '爸爸的哥哥的儿子的妻子' },
    'f.os.d.d': { term: '表外甥女', explanation: '爸爸的姐姐的女儿的女儿' },
    'f.os.d.h': { term: '表姐夫', explanation: '爸爸的姐姐的女儿的丈夫' },
    'f.os.d.s': { term: '表外甥', explanation: '爸爸的姐姐的女儿的儿子' },
    'f.os.s.d': { term: '表侄女', explanation: '爸爸的姐姐的儿子的女儿' },
    'f.os.s.s': { term: '表侄', explanation: '爸爸的姐姐的儿子的儿子' },
    'f.os.s.w': { term: '表嫂', explanation: '爸爸的姐姐的儿子的妻子' },
    'h.f.f.f': { term: '曾祖公父', explanation: '丈夫的爸爸的爸爸的爸爸' },
    'h.f.f.m': { term: '曾祖婆母', explanation: '丈夫的爸爸的爸爸的妈妈' },
    'h.f.lb.w': { term: '叔婆母', explanation: '丈夫的爸爸的弟弟的妻子' },
    'h.f.ls.h': { term: '姑公父', explanation: '丈夫的爸爸的妹妹的丈夫' },
    'h.f.m.f': { term: '曾外祖公父', explanation: '丈夫的爸爸的妈妈的爸爸' },
    'h.f.m.m': { term: '曾外祖婆母', explanation: '丈夫的爸爸的妈妈的妈妈' },
    'h.f.ob.w': { term: '伯婆母', explanation: '丈夫的爸爸的哥哥的妻子' },
    'h.f.os.h': { term: '姑公父', explanation: '丈夫的爸爸的姐姐的丈夫' },
    'h.m.f.f': { term: '外曾祖公父', explanation: '丈夫的妈妈的爸爸的爸爸' },
    'h.m.f.m': { term: '外曾祖婆母', explanation: '丈夫的妈妈的爸爸的妈妈' },
    'h.m.lb.w': { term: '舅婆母', explanation: '丈夫的妈妈的弟弟的妻子' },
    'h.m.ls.h': { term: '姨公父', explanation: '丈夫的妈妈的妹妹的丈夫' },
    'h.m.m.f': { term: '外曾外祖公父', explanation: '丈夫的妈妈的妈妈的爸爸' },
    'h.m.m.m': { term: '外曾外祖婆母', explanation: '丈夫的妈妈的妈妈的妈妈' },
    'h.m.ob.w': { term: '舅婆母', explanation: '丈夫的妈妈的哥哥的妻子' },
    'h.m.os.h': { term: '姨公父', explanation: '丈夫的妈妈的姐姐的丈夫' },
    'm.f.f.f': { term: '外高祖父', explanation: '妈妈的爸爸的爸爸的爸爸' },
    'm.f.f.m': { term: '外高祖母', explanation: '妈妈的爸爸的爸爸的妈妈' },
    'm.f.lb.d': { term: '堂姨', explanation: '妈妈的爸爸的弟弟的女儿' },
    'm.f.lb.s': { term: '堂舅', explanation: '妈妈的爸爸的弟弟的儿子' },
    'm.f.lb.w': { term: '叔外婆', explanation: '妈妈的爸爸的弟弟的妻子' },
    'm.f.ls.d': { term: '表姨', explanation: '妈妈的爸爸的妹妹的女儿' },
    'm.f.ls.h': { term: '姑外公', explanation: '妈妈的爸爸的妹妹的丈夫' },
    'm.f.ls.s': { term: '表舅', explanation: '妈妈的爸爸的妹妹的儿子' },
    'm.f.m.f': { term: '外高外祖父', explanation: '妈妈的爸爸的妈妈的爸爸' },
    'm.f.m.m': { term: '外高外祖母', explanation: '妈妈的爸爸的妈妈的妈妈' },
    'm.f.ob.d': { term: '堂姨', explanation: '妈妈的爸爸的哥哥的女儿' },
    'm.f.ob.s': { term: '堂舅', explanation: '妈妈的爸爸的哥哥的儿子' },
    'm.f.ob.w': { term: '伯外婆', explanation: '妈妈的爸爸的哥哥的妻子' },
    'm.f.os.d': { term: '表姨', explanation: '妈妈的爸爸的姐姐的女儿' },
    'm.f.os.h': { term: '姑外公', explanation: '妈妈的爸爸的姐姐的丈夫' },
    'm.f.os.s': { term: '表舅', explanation: '妈妈的爸爸的姐姐的儿子' },
    'm.lb.d.d': { term: '表外甥女', explanation: '妈妈的弟弟的女儿的女儿' },
    'm.lb.d.h': { term: '表妹夫', explanation: '妈妈的弟弟的女儿的丈夫' },
    'm.lb.d.s': { term: '表外甥', explanation: '妈妈的弟弟的女儿的儿子' },
    'm.lb.s.d': { term: '表侄女', explanation: '妈妈的弟弟的儿子的女儿' },
    'm.lb.s.s': { term: '表侄', explanation: '妈妈的弟弟的儿子的儿子' },
    'm.lb.s.w': { term: '表弟妹', explanation: '妈妈的弟弟的儿子的妻子' },
    'm.ls.d.d': { term: '表外甥女', explanation: '妈妈的妹妹的女儿的女儿' },
    'm.ls.d.h': { term: '表妹夫', explanation: '妈妈的妹妹的女儿的丈夫' },
    'm.ls.d.s': { term: '表外甥', explanation: '妈妈的妹妹的女儿的儿子' },
    'm.ls.s.d': { term: '表侄女', explanation: '妈妈的妹妹的儿子的女儿' },
    'm.ls.s.s': { term: '表侄', explanation: '妈妈的妹妹的儿子的儿子' },
    'm.ls.s.w': { term: '表弟妹', explanation: '妈妈的妹妹的儿子的妻子' },
    'm.m.f.f': { term: '外曾外曾祖父', explanation: '妈妈的妈妈的爸爸的爸爸' },
    'm.m.f.m': { term: '外曾外曾祖母', explanation: '妈妈的妈妈的爸爸的妈妈' },
    'm.m.lb.d': { term: '舅表姨', explanation: '妈妈的妈妈的弟弟的女儿' },
    'm.m.lb.s': { term: '舅表舅', explanation: '妈妈的妈妈的弟弟的儿子' },
    'm.m.lb.w': { term: '舅外婆', explanation: '妈妈的妈妈的弟弟的妻子' },
    'm.m.ls.d': { term: '姨表姨', explanation: '妈妈的妈妈的妹妹的女儿' },
    'm.m.ls.h': { term: '姨外公', explanation: '妈妈的妈妈的妹妹的丈夫' },
    'm.m.ls.s': { term: '姨表舅', explanation: '妈妈的妈妈的妹妹的儿子' },
    'm.m.m.f': { term: '外曾外曾外祖父', explanation: '妈妈的妈妈的妈妈的爸爸' },
    'm.m.m.m': { term: '外曾外曾外祖母', explanation: '妈妈的妈妈的妈妈的妈妈' },
    'm.m.ob.d': { term: '舅表姨', explanation: '妈妈的妈妈的哥哥的女儿' },
    'm.m.ob.s': { term: '舅表舅', explanation: '妈妈的妈妈的哥哥的儿子' },
    'm.m.ob.w': { term: '舅外婆', explanation: '妈妈的妈妈的哥哥的妻子' },
    'm.m.os.d': { term: '姨表姨', explanation: '妈妈的妈妈的姐姐的女儿' },
    'm.m.os.h': { term: '姨外公', explanation: '妈妈的妈妈的姐姐的丈夫' },
    'm.m.os.s': { term: '姨表舅', explanation: '妈妈的妈妈的姐姐的儿子' },
    'm.ob.d.d': { term: '表外甥女', explanation: '妈妈的哥哥的女儿的女儿' },
    'm.ob.d.h': { term: '表姐夫', explanation: '妈妈的哥哥的女儿的丈夫' },
    'm.ob.d.s': { term: '表外甥', explanation: '妈妈的哥哥的女儿的儿子' },
    'm.ob.s.d': { term: '表侄女', explanation: '妈妈的哥哥的儿子的女儿' },
    'm.ob.s.s': { term: '表侄', explanation: '妈妈的哥哥的儿子的儿子' },
    'm.ob.s.w': { term: '表嫂', explanation: '妈妈的哥哥的儿子的妻子' },
    'm.os.d.d': { term: '表外甥女', explanation: '妈妈的姐姐的女儿的女儿' },
    'm.os.d.h': { term: '表姐夫', explanation: '妈妈的姐姐的女儿的丈夫' },
    'm.os.d.s': { term: '表外甥', explanation: '妈妈的姐姐的女儿的儿子' },
    'm.os.s.d': { term: '表侄女', explanation: '妈妈的姐姐的儿子的女儿' },
    'm.os.s.s': { term: '表侄', explanation: '妈妈的姐姐的儿子的儿子' },
    'm.os.s.w': { term: '表嫂', explanation: '妈妈的姐姐的儿子的妻子' },
    's.d.d.d': { term: '曾外曾外孙女', explanation: '儿子的女儿的女儿的女儿' },
    's.d.d.h': { term: '曾外孙女婿', explanation: '儿子的女儿的女儿的丈夫' },
    's.d.d.s': { term: '曾外曾外孙', explanation: '儿子的女儿的女儿的儿子' },
    's.d.s.d': { term: '曾外曾孙女', explanation: '儿子的女儿的儿子的女儿' },
    's.d.s.s': { term: '曾外曾孙', explanation: '儿子的女儿的儿子的儿子' },
    's.d.s.w': { term: '曾外孙媳妇', explanation: '儿子的女儿的儿子的妻子' },
    's.s.d.d': { term: '玄外孙女', explanation: '儿子的儿子的女儿的女儿' },
    's.s.d.h': { term: '曾孙女婿', explanation: '儿子的儿子的女儿的丈夫' },
    's.s.d.s': { term: '玄外孙', explanation: '儿子的儿子的女儿的儿子' },
    's.s.s.d': { term: '玄孙女', explanation: '儿子的儿子的儿子的女儿' },
    's.s.s.s': { term: '玄孙', explanation: '儿子的儿子的儿子的儿子' },
    's.s.s.w': { term: '曾孙妇', explanation: '儿子的儿子的儿子的妻子' },
    's.w.f.f': { term: '姻伯', explanation: '儿子的妻子的爸爸的爸爸' },
    's.w.lb.d': { term: '姻侄孙女', explanation: '儿子的妻子的弟弟的女儿' },
    's.w.lb.s': { term: '姻侄孙', explanation: '儿子的妻子的弟弟的儿子' },
    's.w.lb.w': { term: '姻侄媳', explanation: '儿子的妻子的弟弟的妻子' },
    's.w.ls.d': { term: '姻侄外孙女', explanation: '儿子的妻子的妹妹的女儿' },
    's.w.ls.h': { term: '姻侄婿', explanation: '儿子的妻子的妹妹的丈夫' },
    's.w.ls.s': { term: '姻侄外孙', explanation: '儿子的妻子的妹妹的儿子' },
    's.w.ob.d': { term: '姻侄孙女', explanation: '儿子的妻子的哥哥的女儿' },
    's.w.ob.s': { term: '姻侄孙', explanation: '儿子的妻子的哥哥的儿子' },
    's.w.ob.w': { term: '姻侄媳', explanation: '儿子的妻子的哥哥的妻子' },
    's.w.os.d': { term: '姻侄外孙女', explanation: '儿子的妻子的姐姐的女儿' },
    's.w.os.h': { term: '姻侄婿', explanation: '儿子的妻子的姐姐的丈夫' },
    's.w.os.s': { term: '姻侄外孙', explanation: '儿子的妻子的姐姐的儿子' },
    'w.f.f.f': { term: '曾祖岳父', explanation: '妻子的爸爸的爸爸的爸爸' },
    'w.f.f.m': { term: '曾祖岳母', explanation: '妻子的爸爸的爸爸的妈妈' },
    'w.f.lb.w': { term: '叔岳母', explanation: '妻子的爸爸的弟弟的妻子' },
    'w.f.m.f': { term: '曾外祖岳父', explanation: '妻子的爸爸的妈妈的爸爸' },
    'w.f.m.m': { term: '曾外祖岳母', explanation: '妻子的爸爸的妈妈的妈妈' },
    'w.f.ob.w': { term: '伯岳母', explanation: '妻子的爸爸的哥哥的妻子' },
    'w.m.f.f': { term: '外曾祖岳父', explanation: '妻子的妈妈的爸爸的爸爸' },
    'w.m.f.m': { term: '外曾祖岳母', explanation: '妻子的妈妈的爸爸的妈妈' },
    'w.m.m.f': { term: '外曾外祖岳父', explanation: '妻子的妈妈的妈妈的爸爸' },
    'w.m.m.m': { term: '外曾外祖岳母', explanation: '妻子的妈妈的妈妈的妈妈' },
    'd.d.d.d.h': { term: '外曾外曾外孙女婿', explanation: '女儿的女儿的女儿的女儿的丈夫' },
    'd.d.d.s.w': { term: '外曾外曾外孙媳妇', explanation: '女儿的女儿的女儿的儿子的妻子' },
    'd.d.s.d.h': { term: '外曾外曾孙女婿', explanation: '女儿的女儿的儿子的女儿的丈夫' },
    'd.d.s.s.w': { term: '外曾外曾孙媳妇', explanation: '女儿的女儿的儿子的儿子的妻子' },
    'd.s.d.d.h': { term: '外玄外孙女婿', explanation: '女儿的儿子的女儿的女儿的丈夫' },
    'd.s.d.s.w': { term: '外玄外孙媳妇', explanation: '女儿的儿子的女儿的儿子的妻子' },
    'd.s.s.d.h': { term: '外玄孙女婿', explanation: '女儿的儿子的儿子的女儿的丈夫' },
    'd.s.s.s.w': { term: '外玄孙媳妇', explanation: '女儿的儿子的儿子的儿子的妻子' },
    'f.f.f.f.f': { term: '天祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.lb': { term: '伯叔高祖父', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟' },
    'f.f.f.f.m': { term: '天祖母', explanation: '爸爸的爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.f.ob': { term: '伯叔高祖父', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥' },
    'f.f.f.lb.s': { term: '堂伯叔祖父', explanation: '爸爸的爸爸的爸爸的弟弟的儿子' },
    'f.f.f.lb.w': { term: '伯叔曾祖母', explanation: '爸爸的爸爸的爸爸的弟弟的妻子' },
    'f.f.f.ob.s': { term: '堂伯叔祖父', explanation: '爸爸的爸爸的爸爸的哥哥的儿子' },
    'f.f.f.ob.w': { term: '伯叔曾祖母', explanation: '爸爸的爸爸的爸爸的哥哥的妻子' },
    'f.f.lb.d.h': { term: '堂姑丈', explanation: '爸爸的爸爸的弟弟的女儿的丈夫' },
    'f.f.lb.s.s': { term: '从堂弟', explanation: '爸爸的爸爸的弟弟的儿子的儿子' },
    'f.f.lb.s.w': { term: '堂婶', explanation: '爸爸的爸爸的弟弟的儿子的妻子' },
    'f.f.ob.d.h': { term: '堂姑丈', explanation: '爸爸的爸爸的哥哥的女儿的丈夫' },
    'f.f.ob.s.s': { term: '从堂兄', explanation: '爸爸的爸爸的哥哥的儿子的儿子' },
    'f.f.ob.s.w': { term: '堂伯母', explanation: '爸爸的爸爸的哥哥的儿子的妻子' },
    'f.lb.d.d.h': { term: '堂外甥女婿', explanation: '爸爸的弟弟的女儿的女儿的丈夫' },
    'f.lb.d.s.w': { term: '堂外甥媳妇', explanation: '爸爸的弟弟的女儿的儿子的妻子' },
    'f.lb.s.d.h': { term: '堂侄女婿', explanation: '爸爸的弟弟的儿子的女儿的丈夫' },
    'f.lb.s.s.s': { term: '堂侄孙', explanation: '爸爸的弟弟的儿子的儿子的儿子' },
    'f.lb.s.s.w': { term: '堂侄媳妇', explanation: '爸爸的弟弟的儿子的儿子的妻子' },
    'f.ob.d.d.h': { term: '堂外甥女婿', explanation: '爸爸的哥哥的女儿的女儿的丈夫' },
    'f.ob.d.s.w': { term: '堂外甥媳妇', explanation: '爸爸的哥哥的女儿的儿子的妻子' },
    'f.ob.s.d.h': { term: '堂侄女婿', explanation: '爸爸的哥哥的儿子的女儿的丈夫' },
    'f.ob.s.s.s': { term: '堂侄孙', explanation: '爸爸的哥哥的儿子的儿子的儿子' },
    'f.ob.s.s.w': { term: '堂侄媳妇', explanation: '爸爸的哥哥的儿子的儿子的妻子' },
    'h.f.f.f.lb': { term: '叔曾祖公父', explanation: '丈夫的爸爸的爸爸的爸爸的弟弟' },
    'h.f.f.f.ls': { term: '姑曾祖婆母', explanation: '丈夫的爸爸的爸爸的爸爸的妹妹' },
    'h.f.f.f.ob': { term: '伯曾祖公父', explanation: '丈夫的爸爸的爸爸的爸爸的哥哥' },
    'h.f.f.f.os': { term: '姑曾祖婆母', explanation: '丈夫的爸爸的爸爸的爸爸的姐姐' },
    'm.f.lb.d.h': { term: '堂姨丈', explanation: '妈妈的爸爸的弟弟的女儿的丈夫' },
    'm.f.lb.s.w': { term: '堂舅妈', explanation: '妈妈的爸爸的弟弟的儿子的妻子' },
    'm.f.ls.d.h': { term: '表姨父', explanation: '妈妈的爸爸的妹妹的女儿的丈夫' },
    'm.f.ls.s.w': { term: '表舅妈', explanation: '妈妈的爸爸的妹妹的儿子的妻子' },
    'm.f.ob.d.h': { term: '堂姨丈', explanation: '妈妈的爸爸的哥哥的女儿的丈夫' },
    'm.f.ob.s.w': { term: '堂舅妈', explanation: '妈妈的爸爸的哥哥的儿子的妻子' },
    'm.f.os.d.h': { term: '表姨父', explanation: '妈妈的爸爸的姐姐的女儿的丈夫' },
    'm.f.os.s.w': { term: '表舅妈', explanation: '妈妈的爸爸的姐姐的儿子的妻子' },
    's.d.d.d.h': { term: '曾外曾外孙女婿', explanation: '儿子的女儿的女儿的女儿的丈夫' },
    's.d.d.s.w': { term: '曾外曾外孙媳妇', explanation: '儿子的女儿的女儿的儿子的妻子' },
    's.d.s.d.h': { term: '曾外曾孙女婿', explanation: '儿子的女儿的儿子的女儿的丈夫' },
    's.d.s.s.w': { term: '曾外曾孙媳妇', explanation: '儿子的女儿的儿子的儿子的妻子' },
    's.s.d.d.h': { term: '玄外孙女婿', explanation: '儿子的儿子的女儿的女儿的丈夫' },
    's.s.d.s.w': { term: '玄外孙媳妇', explanation: '儿子的儿子的女儿的儿子的妻子' },
    's.s.s.d.d': { term: '来外孙女', explanation: '儿子的儿子的儿子的女儿的女儿' },
    's.s.s.d.h': { term: '玄孙女婿', explanation: '儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.d.s': { term: '来外孙', explanation: '儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.d': { term: '来孙女', explanation: '儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s': { term: '来孙', explanation: '儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.w': { term: '玄孙媳妇', explanation: '儿子的儿子的儿子的儿子的妻子' },
    'w.f.f.lb.s': { term: '姻叔丈', explanation: '妻子的爸爸的爸爸的弟弟的儿子' },
    'w.f.f.ob.s': { term: '姻伯丈', explanation: '妻子的爸爸的爸爸的哥哥的儿子' },
    'f.f.f.f.f.f': { term: '烈祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.f.m': { term: '烈祖母', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.f.lb.s': { term: '堂伯叔曾祖父', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟的儿子' },
    'f.f.f.f.lb.w': { term: '伯叔高祖母', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟的妻子' },
    'f.f.f.f.ob.s': { term: '堂伯叔曾祖父', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥的儿子' },
    'f.f.f.f.ob.w': { term: '伯叔高祖母', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥的妻子' },
    'f.f.f.lb.s.s': { term: '从叔父', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的儿子' },
    'f.f.f.lb.s.w': { term: '堂伯叔祖母', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的妻子' },
    'f.f.f.ob.s.s': { term: '从伯父', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的儿子' },
    'f.f.f.ob.s.w': { term: '堂伯叔祖母', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的妻子' },
    'f.f.lb.s.s.s': { term: '从堂侄', explanation: '爸爸的爸爸的弟弟的儿子的儿子的儿子' },
    'f.f.ob.s.s.s': { term: '从堂侄', explanation: '爸爸的爸爸的哥哥的儿子的儿子的儿子' },
    'f.lb.s.s.s.s': { term: '堂曾孙', explanation: '爸爸的弟弟的儿子的儿子的儿子的儿子' },
    'f.ob.s.s.s.s': { term: '堂曾孙', explanation: '爸爸的哥哥的儿子的儿子的儿子的儿子' },
    'h.f.f.f.lb.w': { term: '叔曾祖婆母', explanation: '丈夫的爸爸的爸爸的爸爸的弟弟的妻子' },
    'h.f.f.f.ls.h': { term: '姑曾祖公父', explanation: '丈夫的爸爸的爸爸的爸爸的妹妹的丈夫' },
    'h.f.f.f.ob.w': { term: '伯曾祖婆母', explanation: '丈夫的爸爸的爸爸的爸爸的哥哥的妻子' },
    'h.f.f.f.os.h': { term: '姑曾祖公父', explanation: '丈夫的爸爸的爸爸的爸爸的姐姐的丈夫' },
    's.s.s.d.d.h': { term: '来外孙女婿', explanation: '儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.d.s.w': { term: '来外孙媳妇', explanation: '儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.d.d': { term: '晜外孙女', explanation: '儿子的儿子的儿子的儿子的女儿的女儿' },
    's.s.s.s.d.h': { term: '来孙女婿', explanation: '儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.d.s': { term: '晜外孙', explanation: '儿子的儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.s.d': { term: '晜孙女', explanation: '儿子的儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s.s': { term: '晜孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.w': { term: '来孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的妻子' },
    'w.f.f.lb.s.w': { term: '姻婶', explanation: '妻子的爸爸的爸爸的弟弟的儿子的妻子' },
    'w.f.f.ob.s.w': { term: '姻姆', explanation: '妻子的爸爸的爸爸的哥哥的儿子的妻子' },
    'f.f.f.f.f.f.f': { term: '太祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.f.f.m': { term: '太祖母', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.f.lb.s.s': { term: '从伯叔祖父', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟的儿子的儿子' },
    'f.f.f.f.lb.s.w': { term: '堂伯叔曾祖母', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟的儿子的妻子' },
    'f.f.f.f.ob.s.s': { term: '从伯叔祖父', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥的儿子的儿子' },
    'f.f.f.f.ob.s.w': { term: '堂伯叔曾祖母', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥的儿子的妻子' },
    'f.f.f.lb.s.s.s': { term: '族弟', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的儿子的儿子' },
    'f.f.f.lb.s.s.w': { term: '从叔母', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的儿子的妻子' },
    'f.f.f.ob.s.s.s': { term: '族兄', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的儿子的儿子' },
    'f.f.f.ob.s.s.w': { term: '从伯母', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的儿子的妻子' },
    'f.f.lb.s.s.s.s': { term: '从堂侄孙', explanation: '爸爸的爸爸的弟弟的儿子的儿子的儿子的儿子' },
    'f.f.ob.s.s.s.s': { term: '从堂侄孙', explanation: '爸爸的爸爸的哥哥的儿子的儿子的儿子的儿子' },
    'f.lb.s.s.s.s.s': { term: '堂玄孙', explanation: '爸爸的弟弟的儿子的儿子的儿子的儿子的儿子' },
    'f.ob.s.s.s.s.s': { term: '堂玄孙', explanation: '爸爸的哥哥的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.d.d.h': { term: '晜外孙女婿', explanation: '儿子的儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.s.d.s.w': { term: '晜外孙媳妇', explanation: '儿子的儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.s.d.d': { term: '仍外孙女', explanation: '儿子的儿子的儿子的儿子的儿子的女儿的女儿' },
    's.s.s.s.s.d.h': { term: '晜孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.s.d.s': { term: '仍外孙', explanation: '儿子的儿子的儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.s.s.d': { term: '仍孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s.s.s': { term: '仍孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.w': { term: '晜孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的妻子' },
    'f.f.f.f.f.f.f.f': { term: '远祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.f.f.f.m': { term: '远祖母', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.f.lb.s.s.s': { term: '族叔父', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟的儿子的儿子的儿子' },
    'f.f.f.f.lb.s.s.w': { term: '从伯叔祖母', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟的儿子的儿子的妻子' },
    'f.f.f.f.ob.s.s.s': { term: '族伯父', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥的儿子的儿子的儿子' },
    'f.f.f.f.ob.s.s.w': { term: '从伯叔祖母', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥的儿子的儿子的妻子' },
    'f.f.f.lb.s.s.s.s': { term: '族侄', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的儿子的儿子的儿子' },
    'f.f.f.ob.s.s.s.s': { term: '族侄', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的儿子的儿子的儿子' },
    'f.f.lb.s.s.s.s.s': { term: '从堂侄曾孙', explanation: '爸爸的爸爸的弟弟的儿子的儿子的儿子的儿子的儿子' },
    'f.f.ob.s.s.s.s.s': { term: '从堂侄曾孙', explanation: '爸爸的爸爸的哥哥的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.d.d.h': { term: '仍外孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.s.s.d.s.w': { term: '仍外孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.s.s.d.d': { term: '云外孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿' },
    's.s.s.s.s.s.d.h': { term: '仍孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.s.s.d.s': { term: '云外孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.s.s.s.d': { term: '云孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s.s.s.s': { term: '云孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.s.w': { term: '仍孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的妻子' },
    'f.f.f.f.f.f.f.f.f': { term: '鼻祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.f.f.f.f.m': { term: '鼻祖母', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.f.lb.s.s.s.w': { term: '族叔母', explanation: '爸爸的爸爸的爸爸的爸爸的弟弟的儿子的儿子的儿子的妻子' },
    'f.f.f.f.ob.s.s.s.w': { term: '族伯母', explanation: '爸爸的爸爸的爸爸的爸爸的哥哥的儿子的儿子的儿子的妻子' },
    'f.f.f.lb.s.s.s.s.s': { term: '族侄孙', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的儿子的儿子的儿子的儿子' },
    'f.f.f.ob.s.s.s.s.s': { term: '族侄孙', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的儿子的儿子的儿子的儿子' },
    'f.f.lb.s.s.s.s.s.s': { term: '从堂侄玄孙', explanation: '爸爸的爸爸的弟弟的儿子的儿子的儿子的儿子的儿子的儿子' },
    'f.f.ob.s.s.s.s.s.s': { term: '从堂侄玄孙', explanation: '爸爸的爸爸的哥哥的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.d.d.h': { term: '云外孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.s.s.s.d.s.w': { term: '云外孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.s.s.s.d.d': { term: '耳外孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿' },
    's.s.s.s.s.s.s.d.h': { term: '云孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.s.s.s.d.s': { term: '耳外孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.s.s.s.s.d': { term: '耳孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s.s.s.s.s': { term: '耳孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.s.s.w': { term: '云孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的妻子' },
    'f.f.f.f.f.f.f.f.f.f': { term: '开祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.f.f.f.f.f.m': { term: '开祖母', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.lb.s.s.s.s.s.s': { term: '族侄曾孙', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的儿子的儿子的儿子的儿子的儿子' },
    'f.f.f.ob.s.s.s.s.s.s': { term: '族侄曾孙', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.s.d.d.h': { term: '耳外孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.s.s.s.s.d.s.w': { term: '耳外孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.s.s.s.s.d.d': { term: '弥外孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿' },
    's.s.s.s.s.s.s.s.d.h': { term: '耳孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.s.s.s.s.d.s': { term: '弥外孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.s.s.s.s.s.d': { term: '弥孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s.s.s.s.s.s': { term: '弥孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.s.s.s.w': { term: '耳孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的妻子' },
    'f.f.f.f.f.f.f.f.f.f.f': { term: '始祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.f.f.f.f.f.f.m': { term: '始祖母', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的妈妈' },
    'f.f.f.lb.s.s.s.s.s.s.s': { term: '族侄玄孙', explanation: '爸爸的爸爸的爸爸的弟弟的儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    'f.f.f.ob.s.s.s.s.s.s.s': { term: '族侄玄孙', explanation: '爸爸的爸爸的爸爸的哥哥的儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.s.s.d.d.h': { term: '弥外孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.s.s.s.s.s.d.s.w': { term: '弥外孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.s.s.s.s.s.d.d': { term: '胎外孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿' },
    's.s.s.s.s.s.s.s.s.d.h': { term: '弥孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.s.s.s.s.s.d.s': { term: '胎外孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.s.s.s.s.s.s.d': { term: '胎孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s.s.s.s.s.s.s': { term: '胎孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.s.s.s.s.w': { term: '弥孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的妻子' },
    'f.f.f.f.f.f.f.f.f.f.f.f': { term: '先祖父', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸' },
    'f.f.f.f.f.f.f.f.f.f.f.m': { term: '先祖母', explanation: '爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的妈妈' },
    's.s.s.s.s.s.s.s.s.d.d.h': { term: '胎外孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.s.s.s.s.s.s.d.s.w': { term: '胎外孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.s.s.s.s.s.s.d.d': { term: '承外孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿' },
    's.s.s.s.s.s.s.s.s.s.d.h': { term: '胎孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.s.s.s.s.s.s.d.s': { term: '承外孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子' },
    's.s.s.s.s.s.s.s.s.s.s.d': { term: '承孙女', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿' },
    's.s.s.s.s.s.s.s.s.s.s.s': { term: '承孙', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子' },
    's.s.s.s.s.s.s.s.s.s.s.w': { term: '胎孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的妻子' },
    's.s.s.s.s.s.s.s.s.s.d.d.h': { term: '承外孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的女儿的丈夫' },
    's.s.s.s.s.s.s.s.s.s.d.s.w': { term: '承外孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的儿子的妻子' },
    's.s.s.s.s.s.s.s.s.s.s.d.h': { term: '承孙女婿', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的女儿的丈夫' },
    's.s.s.s.s.s.s.s.s.s.s.s.w': { term: '承孙媳妇', explanation: '儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的儿子的妻子' },
  };

  /**
   * Normalize a dot-joined chain by applying reduction rules iteratively.
   */
  function normalize(chain) {
    let prev = '';
    let iterations = 0;
    while (chain !== prev && iterations < 30) {
      prev = chain;
      for (const [pattern, replacement] of RULES) {
        // Only match whole segments (bounded by dots or string edges)
        const escaped = pattern.replace(/\./g, '\\.');
        const re = new RegExp('(?:^|(?<=\\.))' + escaped + '(?=$|(?=\\.))');
        chain = chain.replace(re, replacement);
      }
      // Clean up dots
      chain = chain.replace(/\.{2,}/g, '.').replace(/^\./, '').replace(/\.$/, '');
      iterations++;
    }
    return chain;
  }

  /**
   * Resolve a chain of relationship IDs to a kinship term.
   * @param {string[]} chain - Array of relation IDs from user clicks
   * @returns {{ term: string, explanation: string } | null}
   */
  function resolve(chain) {
    if (!chain || chain.length === 0) return null;

    const key = chain.join('.');

    // 1. Direct lookup
    if (MAP[key]) return MAP[key];

    // 2. Normalize and lookup
    const normalized = normalize(key);
    if (!normalized) return { term: '自己', explanation: '就是你自己' };
    if (MAP[normalized]) return MAP[normalized];

    // 3. Try splitting into known prefix + known suffix
    const parts = normalized.split('.');
    for (let i = parts.length - 1; i >= 1; i--) {
      const prefix = parts.slice(0, i).join('.');
      const suffix = parts.slice(i).join('.');
      if (MAP[prefix] && MAP[suffix]) {
        return {
          term: MAP[prefix].term + '的' + MAP[suffix].term,
          explanation: '较远的亲属关系',
        };
      }
    }

    return null;
  }

  function getRelations() {
    return RELATIONS;
  }

  function getLabel(id) {
    const rel = RELATIONS.find(r => r.id === id);
    return rel ? rel.label : id;
  }

  return { getRelations, resolve, getLabel };
})();
