services:
  wedding-showcase:
    build: .
    container_name: wedding-showcase
    restart: always
    environment:
      - VIRTUAL_HOST=wedding.${S_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=wedding.${S_DOMAIN}
    expose:
      - "80"
